/** Colonnes sélectionnées pour les listes admin inscriptions / paiements. */
export const ADMIN_INSCRIPTION_SELECT = [
  'id',
  'status',
  'annee_scolaire',
  'nom',
  'prenom',
  'email',
  'telephone',
  'date_naissance',
  'adresse',
  'numero_voie',
  'rue',
  'code_postal',
  'ville',
  'responsable_legal',
  'cours_selectionne',
  'inscription_familiale',
  'membre_2',
  'type_tarif',
  'montant_total',
  'certificat_medical_url',
  'autorisation_parentale_url',
  'photo_url',
  'accepte_reglement',
  'accepte_charte',
  'atteste_certificat',
  'certificat_engagement_3_semaines',
  'autorisation_engagement_3_semaines',
  'photo_engagement_3_semaines',
  'autorise_photos',
  'autorise_sortie_seul',
  'autorise_voiture_privee',
  'informe_assurance_individuelle',
  'informe_droit_acces',
  'helloasso_payment_id',
  'helloasso_payment_url',
  'date_paiement',
  'mode_paiement',
  'nombre_echeances',
  'montant_paye',
  'taille_cm',
  'poids_kg',
  'taille_tenue',
  'sexe',
  'type_profil',
  'dossier_status',
  'attestation_questionnaire_sante',
  'autorisation_pratique_mineur',
  'autorisation_soins_urgence',
  'accepte_rgpd',
  'documents_token',
  'created_at',
  'updated_at',
  'expires_at',
].join(', ');

export const PAGE_SIZE_INSCRIPTIONS = 25;
